version: '3.5'

services:
  php-fpm:
    platform: ${PLATFORM}
    build: ./docker/php
    container_name: ${APP_PREFIX}-php
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env
  nginx:
    platform: ${PLATFORM}
    image: nginx:latest
    container_name: ${APP_PREFIX}-nginx
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    ports:
      - ${DEV_IP}:${DEV_PORT}:80
    depends_on:
      - php-fpm
  db:
    platform: ${PLATFORM}
    image: mariadb:latest
    container_name: ${APP_PREFIX}-db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Europe/Prague
    ports:
      - ${DEV_IP}:3306:3306
  adminer:
    platform: ${PLATFORM}
    image: adminer:latest
    container_name: ${APP_PREFIX}-adminer
    ports:
      - ${DEV_IP}:8080:8080

volumes:
  db: